  0%|                                                | 0/107345 [00:00<?, ?it/s]/home/rilyn/anaconda3/envs/lmms-finetune/lib/python3.10/site-packages/torch/utils/checkpoint.py:87: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
  warnings.warn(
`use_cache=True` is incompatible with gradient checkpointing. Setting `use_cache=False`.
Starting from v4.46, the `logits` model output will have the same type as the model (except at train time, where it will always be FP32)
  0%|                                   | 11/107345 [01:28<141:30:18,  4.75s/it]Traceback (most recent call last):
{'loss': 0.0, 'grad_norm': 0.0, 'learning_rate': 6.209251785159889e-09, 'epoch': 0.0}
{'loss': 0.0, 'grad_norm': 0.0, 'learning_rate': 1.2418503570319778e-08, 'epoch': 0.0}
{'loss': 0.0, 'grad_norm': 0.0, 'learning_rate': 1.8627755355479668e-08, 'epoch': 0.0}
{'loss': 0.0, 'grad_norm': 0.0, 'learning_rate': 2.4837007140639555e-08, 'epoch': 0.0}
{'loss': 0.0, 'grad_norm': 0.0, 'learning_rate': 3.104625892579944e-08, 'epoch': 0.0}
{'loss': 0.0, 'grad_norm': 0.0, 'learning_rate': 3.7255510710959337e-08, 'epoch': 0.0}
{'loss': 0.0, 'grad_norm': 0.0, 'learning_rate': 4.346476249611922e-08, 'epoch': 0.0}
{'loss': 0.0, 'grad_norm': 0.0, 'learning_rate': 4.967401428127911e-08, 'epoch': 0.0}
{'loss': 0.0, 'grad_norm': 0.0, 'learning_rate': 5.5883266066439e-08, 'epoch': 0.0}
{'loss': 0.0, 'grad_norm': 0.0, 'learning_rate': 6.209251785159889e-08, 'epoch': 0.0}
{'loss': 0.0, 'grad_norm': 0.0, 'learning_rate': 6.830176963675877e-08, 'epoch': 0.0}
  File "/home/rilyn/project-files/01-pj-moog/moog-pipeline-ft/lmms-finetune/train.py", line 201, in <module>
    train()
  File "/home/rilyn/project-files/01-pj-moog/moog-pipeline-ft/lmms-finetune/train.py", line 194, in train
    trainer.train()
  File "/home/rilyn/anaconda3/envs/lmms-finetune/lib/python3.10/site-packages/transformers/trainer.py", line 2052, in train
    return inner_training_loop(
  File "/home/rilyn/anaconda3/envs/lmms-finetune/lib/python3.10/site-packages/transformers/trainer.py", line 2345, in _inner_training_loop
    for step, inputs in enumerate(epoch_iterator):
  File "/home/rilyn/anaconda3/envs/lmms-finetune/lib/python3.10/site-packages/accelerate/data_loader.py", line 574, in __iter__
    next_batch = next(dataloader_iter)
  File "/home/rilyn/anaconda3/envs/lmms-finetune/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 708, in __next__
    data = self._next_data()
  File "/home/rilyn/anaconda3/envs/lmms-finetune/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1455, in _next_data
    return self._process_data(data)
  File "/home/rilyn/anaconda3/envs/lmms-finetune/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1505, in _process_data
    data.reraise()
  File "/home/rilyn/anaconda3/envs/lmms-finetune/lib/python3.10/site-packages/torch/_utils.py", line 733, in reraise
    raise exception
TypeError: Caught TypeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/rilyn/anaconda3/envs/lmms-finetune/lib/python3.10/site-packages/torch/utils/data/_utils/worker.py", line 349, in _worker_loop
    data = fetcher.fetch(index)  # type: ignore[possibly-undefined]
  File "/home/rilyn/anaconda3/envs/lmms-finetune/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 55, in fetch
    return self.collate_fn(data)
  File "/home/rilyn/project-files/01-pj-moog/moog-pipeline-ft/lmms-finetune/collators/llava_next_video.py", line 97, in __call__
    temp = self.processor.apply_chat_template(
  File "/home/rilyn/anaconda3/envs/lmms-finetune/lib/python3.10/site-packages/transformers/processing_utils.py", line 1072, in apply_chat_template
    return self.tokenizer.apply_chat_template(
  File "/home/rilyn/project-files/01-pj-moog/moog-pipeline-ft/lmms-finetune/collators/chat_template_monkey_patch.py", line 166, in apply_chat_template
    rendered_chat, generation_indices = _render_with_assistant_indices(
  File "/home/rilyn/anaconda3/envs/lmms-finetune/lib/python3.10/site-packages/transformers/utils/chat_template_utils.py", line 348, in _render_with_assistant_indices
    for block in compiled_template.generate(
  File "/home/rilyn/anaconda3/envs/lmms-finetune/lib/python3.10/site-packages/jinja2/environment.py", line 1348, in generate
    yield self.environment.handle_exception()
  File "/home/rilyn/anaconda3/envs/lmms-finetune/lib/python3.10/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<template>", line 3, in top-level template code
  File "/home/rilyn/anaconda3/envs/lmms-finetune/lib/python3.10/site-packages/jinja2/sandbox.py", line 401, in call
    return __context.call(__obj, *args, **kwargs)
  File "/home/rilyn/anaconda3/envs/lmms-finetune/lib/python3.10/site-packages/transformers/utils/chat_template_utils.py", line 380, in _generation_support
    rv = caller()
  File "/home/rilyn/anaconda3/envs/lmms-finetune/lib/python3.10/site-packages/jinja2/runtime.py", line 784, in _invoke
    rv = self._func(*arguments)
  File "<template>", line 3, in template
TypeError: unsupported operand type(s) for +: 'int' and 'str'

[rank0]: Traceback (most recent call last):
[rank0]:   File "/home/rilyn/project-files/01-pj-moog/moog-pipeline-ft/lmms-finetune/train.py", line 201, in <module>
[rank0]:     train()
[rank0]:   File "/home/rilyn/project-files/01-pj-moog/moog-pipeline-ft/lmms-finetune/train.py", line 194, in train
[rank0]:     trainer.train()
[rank0]:   File "/home/rilyn/anaconda3/envs/lmms-finetune/lib/python3.10/site-packages/transformers/trainer.py", line 2052, in train
[rank0]:     return inner_training_loop(
[rank0]:   File "/home/rilyn/anaconda3/envs/lmms-finetune/lib/python3.10/site-packages/transformers/trainer.py", line 2345, in _inner_training_loop
[rank0]:     for step, inputs in enumerate(epoch_iterator):
[rank0]:   File "/home/rilyn/anaconda3/envs/lmms-finetune/lib/python3.10/site-packages/accelerate/data_loader.py", line 574, in __iter__
[rank0]:     next_batch = next(dataloader_iter)
[rank0]:   File "/home/rilyn/anaconda3/envs/lmms-finetune/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 708, in __next__
[rank0]:     data = self._next_data()
[rank0]:   File "/home/rilyn/anaconda3/envs/lmms-finetune/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1455, in _next_data
[rank0]:     return self._process_data(data)
[rank0]:   File "/home/rilyn/anaconda3/envs/lmms-finetune/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1505, in _process_data
[rank0]:     data.reraise()
[rank0]:   File "/home/rilyn/anaconda3/envs/lmms-finetune/lib/python3.10/site-packages/torch/_utils.py", line 733, in reraise
[rank0]:     raise exception
[rank0]: TypeError: Caught TypeError in DataLoader worker process 0.
[rank0]: Original Traceback (most recent call last):
[rank0]:   File "/home/rilyn/anaconda3/envs/lmms-finetune/lib/python3.10/site-packages/torch/utils/data/_utils/worker.py", line 349, in _worker_loop
[rank0]:     data = fetcher.fetch(index)  # type: ignore[possibly-undefined]
[rank0]:   File "/home/rilyn/anaconda3/envs/lmms-finetune/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 55, in fetch
[rank0]:     return self.collate_fn(data)
[rank0]:   File "/home/rilyn/project-files/01-pj-moog/moog-pipeline-ft/lmms-finetune/collators/llava_next_video.py", line 97, in __call__
[rank0]:     temp = self.processor.apply_chat_template(
[rank0]:   File "/home/rilyn/anaconda3/envs/lmms-finetune/lib/python3.10/site-packages/transformers/processing_utils.py", line 1072, in apply_chat_template
[rank0]:     return self.tokenizer.apply_chat_template(
[rank0]:   File "/home/rilyn/project-files/01-pj-moog/moog-pipeline-ft/lmms-finetune/collators/chat_template_monkey_patch.py", line 166, in apply_chat_template
[rank0]:     rendered_chat, generation_indices = _render_with_assistant_indices(
[rank0]:   File "/home/rilyn/anaconda3/envs/lmms-finetune/lib/python3.10/site-packages/transformers/utils/chat_template_utils.py", line 348, in _render_with_assistant_indices
[rank0]:     for block in compiled_template.generate(
[rank0]:   File "/home/rilyn/anaconda3/envs/lmms-finetune/lib/python3.10/site-packages/jinja2/environment.py", line 1348, in generate
[rank0]:     yield self.environment.handle_exception()
[rank0]:   File "/home/rilyn/anaconda3/envs/lmms-finetune/lib/python3.10/site-packages/jinja2/environment.py", line 942, in handle_exception
[rank0]:     raise rewrite_traceback_stack(source=source)
[rank0]:   File "<template>", line 3, in top-level template code
[rank0]:   File "/home/rilyn/anaconda3/envs/lmms-finetune/lib/python3.10/site-packages/jinja2/sandbox.py", line 401, in call
[rank0]:     return __context.call(__obj, *args, **kwargs)
[rank0]:   File "/home/rilyn/anaconda3/envs/lmms-finetune/lib/python3.10/site-packages/transformers/utils/chat_template_utils.py", line 380, in _generation_support
[rank0]:     rv = caller()
[rank0]:   File "/home/rilyn/anaconda3/envs/lmms-finetune/lib/python3.10/site-packages/jinja2/runtime.py", line 784, in _invoke
[rank0]:     rv = self._func(*arguments)
[rank0]:   File "<template>", line 3, in template
[rank0]: TypeError: unsupported operand type(s) for +: 'int' and 'str'
